# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: nmuresan <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2015/09/16 18:04:15 by nmuresan          #+#    #+#              #
#    Updated: 2015/09/16 18:26:15 by nmuresan         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = do-op
SRC = afisare.c functii.c main.c operator.c 
FLAGS = -Wall -Wextra -Werror
OPTIONS = -o do-op
all: $(NAME)

$(NAME):
	gcc $(FLAGS) $(OPTIONS) $(SRC)

clean:
	*/* -f *.c
